### ISSUE TITLE
Null reference error

### ISSUE THREAD

**Issue by RoarkDude** [agileharbor/magentoAccess#3]
Hi,

Creating a service requires additional parameters not specified in the documentation.  I guessed and used:

```
            int productThreadsLimit = 100;
            int sessionLifeTimeMs = 10000;
            bool isLogRawMessages = true;
```

Also, left Soap parameters as empty strings.

```
            var servicesFactory = new MagentoFactory();
            var magentoService = servicesFactory.CreateService(new MagentoAuthenticatedUserCredentials(accessToken, accessTokenSecret, storeURL, consumerSecret, consumerKey, "", "", productThreadsLimit,sessionLifeTimeMs,isLogRawMessages), new MagentoConfig() { EditionByDefault = "ce", VersionByDefault = "2.0.2.0" });

var margentoOrders = magentoService.GetOrdersAsync().Result;

```
Should return the 2 orders in the test webstore.  The API call works using Postman with the same credentials.  This throws and exception (same for GetProductsAsync()):

System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MagentoClient.Program.Main(String[] args) in C:\Users\Peter\magentoAccess-master\src\MagentoClient\Program.cs:line 29

Inner Exception 1:
MagentoCommonException: GetOrdersAsync:{MethodName:GetOrdersAsync, ConnectionInfo:{"StoreVersion":"2.0.2.0","ApiUser":"","ApiKey":"","Store":null,"BaseMagentoUrl":"http://localhost/Magento","TokenSecret":null,"LogRawMessages":true,"GetStockItemsWithoutSkuImplementedWithPages":true,"GetOrderByIdForFullInformation":true,"GetOrdersUsesEntityInsteadOfIncrementId":true}, MethodParameters:, Mark:"826af4bc-2bd5-4998-9404-4fb5e35e7af4", {}}

Inner Exception 2:
NullReferenceException: Object reference not set to an instance of an object.

**Comment by MaximKitsenko** [comment]
@RoarkDude 
What version of magento do you use?
Looks like you use incorrect credentials. I have updated documentation try to use parameters like in documentation.
Does it work now?

**Comment by RoarkDude** [comment]
Hi,
I'm using 2.1.5. I'm still getting the same error.  I'm trying to use rest like this:

```
            var servicesFactory = new MagentoFactory();
            var magentoService = servicesFactory.CreateService(new MagentoAuthenticatedUserCredentials(accessToken, accessTokenSecret, storeURL, consumerSecret, consumerKey, "", "", productThreadsLimit,sessionLifeTimeMs,isLogRawMessages), new MagentoConfig() { EditionByDefault = "ce", VersionByDefault = "2.1.5.0", Protocol=MagentoDefaultProtocol.RestOnly});

```
My credentials are ok.  I know because they work when using Postman

**Comment by MaximKitsenko** [comment]
@RoarkDude yes, your credentials can be ok, but you don't pass them to the function. I mean you use incorrect arguments. 
Look to the documentation for correct example:
`var magentoService = servicesFactory.CreateService(new MagentoAuthenticatedUserCredentials( "n/a", "n/a", "https://www.youstore.com", "n/a", "n/a", "User", "Password", 4, 1800000, false ), new MagentoConfig() { EditionByDefault = "ce", VersionByDefault = "2.1.0.0", Protocol = MagentoDefaultProtocol.SoapOnly } );`

but insteadof  "User", "Password" you use "" and "":
var magentoService = servicesFactory.CreateService(new MagentoAuthenticatedUserCredentials(accessToken, accessTokenSecret, storeURL, consumerSecret, consumerKey, "", "", productThreadsLimit,sessionLifeTimeMs,isLogRawMessages), new MagentoConfig() { EditionByDefault = "ce", VersionByDefault = "2.1.5.0", Protocol=MagentoDefaultProtocol.RestOnly});

**Comment by RoarkDude** [comment]
Right, I don't want to use soap, I want to use rest.  I tried putting "n/a" for soap user and password but still same error.  Maybe you can document an an example using

` Protocol=MagentoDefaultProtocol.RestOnly
`
You get the rest API credentials from the Magento Admin screen.  System-Integrations.  Add an Integration and you'll get the 4 keys: accessToken, accessTokenSecret, consumerSecret, consumerKey

Thanks.

**Comment by MaximKitsenko** [comment]
@RoarkDude in general 4 keys from magento store : accessToken, accessTokenSecret, consumerSecret, consumerKey doesn't make sense, because you can always accesss your store API just with store simple user credentials. At this moment only this way supported, later i will added support for these 4 keys.

So, to start working, you should create user (system->all users), add correct permissons for that user.

Use your user credentials as i wrote above:
`var magentoService = servicesFactory.CreateService(new MagentoAuthenticatedUserCredentials( "n/a", "n/a", "https://www.youstore.com", "n/a", "n/a", "User", "Password", 4, 1800000, false ), new MagentoConfig() { EditionByDefault = "ce", VersionByDefault = "2.1.0.0", Protocol = MagentoDefaultProtocol.SoapOnly } );`

"User" = you store user
"Password" = you store user password

It doesn't metter do you use REST or SOAP, you should always use your user credentials like in example above.

**Comment by RoarkDude** [comment]
Init service? That's not in the documentation at all.  I added it and I'm still getting same errors with

`
`            string storeURL = "http://localhost/Magento";

            var magentoService = servicesFactory.CreateService(new MagentoAuthenticatedUserCredentials("n/a", "n/a", storeURL, "n/a", "n/a", soapUser, soapPassword, productThreadsLimit, sessionLifeTimeMs, isLogRawMessages), new MagentoConfig() { EditionByDefault = "ce", VersionByDefault = "2.1.5.0", Protocol = MagentoDefaultProtocol.SoapOnly });

            bool isInitialized = magentoService.InitAsync().Result;

            if (isInitialized)
            {
                var margentoOrders = magentoService.GetOrdersAsync().Result;
            }
`

I tried both admin user and password and a user I created with and admin role and password.

**Comment by MaximKitsenko** [comment]
@RoarkDude can ypu add complete description of these "some" errors that you receive?

**Comment by RoarkDude** [comment]
Here's the code:

```
            int productThreadsLimit = 4;
            int sessionLifeTimeMs = 180000;
            bool isLogRawMessages = false;
            string storeURL = "http://localhost/Magento";
            string soapUser = "admin";
            string soapPassword = "********";

            var servicesFactory = new MagentoFactory();
            var magentoService = servicesFactory.CreateService(new MagentoAuthenticatedUserCredentials("n/a", "n/a", storeURL, "n/a", "n/a", soapUser, soapPassword, productThreadsLimit, sessionLifeTimeMs, isLogRawMessages), new MagentoConfig() { EditionByDefault = "ce", VersionByDefault = "2.1.5.0", Protocol = MagentoDefaultProtocol.SoapOnly });

            bool isInitialized = magentoService.InitAsync().Result;

            if (isInitialized)
            {
                var margentoOrders = magentoService.GetOrdersAsync().Result;
            }

```

Here's the error.  I think "Store\":null is the is the null reference that's causing the exception:


`
-		InnerException	{"GetOrdersAsync:{MethodName:GetOrdersAsync, ConnectionInfo:{\"StoreVersion\":\"2.1.5.0\",\"ApiUser\":\"admin\",\"ApiKey\":\"Summ!t29\",\"Store\":null,\"BaseMagentoUrl\":\"http://localhost/Magento\",\"TokenSecret\":null,\"LogRawMessages\":false,\"GetStockItemsWithoutSkuImplementedWithPages\":true,\"GetOrderByIdForFullInformation\":true,\"GetOrdersUsesEntityInsteadOfIncrementId\":true}, MethodParameters:, Mark:\"a8c3a5e4-daf4-4fe8-a4dd-1733dadd4024\", {}}"}	System.Exception {MagentoAccess.MagentoCommonException}

		Message	"Object reference not set to an instance of an object."	string

		StackTrace	"   at MagentoAccess.MagentoService.<GetOrdersAsync>d__44.MoveNext() in C:\\work\\SkuVault\\repo\\Integration\\MagentoAccess\\src\\MagentoAccess\\MagentoService.cs:line 497"	string



`

Stack Trace:
`
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MagentoClient.Program.Main(String[] args) in C:\Users\Peter\Documents\Visual Studio 2017\Learning\MagentoClient\MagentoClient\Program.cs:line 36
`

**Comment by MaximKitsenko** [comment]
@RoarkDude
Unfortunately, i have no time to fix it right now.
I suggest you to use another 2 methods:
`public async Task< IEnumerable< Order > > GetOrdersAsync( DateTime dateFrom, DateTime dateTo, Mark mark = null )`
and 
`public async Task< IEnumerable< Order > > GetOrdersAsync( IEnumerable< string > orderIds )`
try to use the.

If you will create a fix for `GetOrdersAsync()` create pull request please.

**Comment by ashishsuvarna** [comment]
Hi I have tried DetermineMagentoVersionAndSetupServiceAsync , GetOrdersAsync with and without dates but nothing seems to work.. Would be nice if you can update this.. This could be quite a useful library.

**Comment by MaximKitsenko** [comment]
@ashishsuvarna, DetermineMagentoVersionAndSetupServiceAsync , GetOrdersAsync works, i tested it on dozens of production stores via SOAP. I think your problem related to incorrect parameters. Look to the Tests there are a lot of examples there.

**Comment by Malfonde** [comment]
Hey,
I am using Magento version 1.9.3.2 , ( I know that officially it has not been tested with MagentoAccess.),
and I get the same error as the above.
I will mention that MagentoService.GetOrdersAsync(DateTime dateFrom ,DateTime dateTo) works just fine with the same request parameters that I have created the service with.

I hope it will help you to find the issue, and maybe solve it for this version too :).
I'll gladly answer any question, 
thank you for your good job!.
